#!/bin/bash
alias a2c='aria2c -s 8 -x 8'
alias ac='autoconf'
alias acs='apt-cache search'
alias am='automake'
alias app='sudo aptitude purge ~c'
alias c="clear"
alias cho='sudo chown -R nsujir'
alias ckp='echo "Signed-off-by: Nithin Sujir" > /tmp/gdckpatch && git diff >> /tmp/gdckpatch && git diff --cached >> /tmp/gdckpatch && ./scripts/checkpatch.pl /tmp/gdckpatch'
alias cls='clear;ls'
alias cpi='cat /proc/interrupts'
alias cpu='cat /proc/cpuinfo'
alias d='cd ..'
alias dis='disper -d DFP-0,DFP-1 -e'
alias disl='disper -d DFP-3 -c'
alias e='evince'
alias eg="export P4DIFF='gvimdiff -f'"
alias ep="export P4DIFF='diff -bru'"
alias f='find . -iname'
alias g3artman="/google/data/ro/teams/oneplatform/g3artman"
alias gar='git am --reject'
alias gcp='git cherry-pick'
alias gd='gitvimdiff'
alias gdc='gitvimdiff --cached'
alias gg4="git status | grep -e modified -e new | awk '{print \$4;}' | xargs gvim"
alias ggc='git gc'
alias gg="git status | grep -e modified -e new | awk '{print \$3;}' | xargs gvim"
alias g='gvim -geometry 135x60'
alias gib='git branch'
alias gica='git commit --amend'
alias gicb='git checkout -b'
alias gic='git commit'
alias gic.='git commit -am .'
alias gich='git checkout'
alias gicl='git clone'
alias gidc='git diff --cached'
alias gid='git diff'
#alias gif='git format-patch -s'
alias gifu='git fetch upstream'
alias gi='grep -I -i -n'
alias gih='git help'
alias gil='git log'
alias giln='gil --name-only'
alias gilp='git log -p'
alias gimb='git checkout master; git branch'
alias gim='git checkout master'
alias gimu='git merge upstream/master'
alias gin='git init && git add . && git commit -am "init" && git gc'
#alias gio='git log --branches --not --remotes=origin'
alias gip='git pull'
alias gir='git reset'
alias GIR='git reset --hard'
alias girH='git rebase -i HEAD~15'
alias girh='git rebase -i HEAD~5'
alias giri='git rebase -i'
alias GIS='git reset --soft'
alias gis='git status'
alias giu='git update-index --assume-unchanged'
alias gmm='git merge master'
alias golv='git am --resolved'
alias gow='git show'
alias gp='g4 pending -s relativepath'
alias grm='git rebase master'
alias gs='gvim -S .gvimsession'
alias gtc='git tag --contains'
alias ha='history -a'
alias hn='history -n'
alias ind='indent -linux -il0 -bad -nbbo'
alias k='killall -9'
alias la='ls -A'
alias lg='ssh lg'
alias lld='ll | grep ^d'
alias ll='ls -l --color'
alias l='ls -CF'
alias loc='locate -i'
#alias ls='ls --color'
alias mck='make menuconfig KCONFIG_CONFIG=arch/x86/configs/tintri.config'
alias mcl='make clean'
alias mc='make menuconfig'
alias md='mkdir'
alias mi='make install'
alias mj='export CPUS=`grep processor /proc/cpuinfo | wc -l`; make -j $[$CPUS*2]'
alias mjmi='export CPUS=`grep processor /proc/cpuinfo | wc -l`; make -j $[$CPUS*2] && sudo make modules_install && sudo make install && sync'
alias mki='mkisofs -l'
alias mm='export CPUS=`grep processor /proc/cpuinfo | wc -l`; make modules -j $[$CPUS*2]'
alias mmi='sudo make modules_install && sync'
alias mmmi='export CPUS=`grep processor /proc/cpuinfo | wc -l`; make modules -j $[$CPUS*2] && sudo make modules_install && sync'
alias mn='mount /media/nseg'
alias mps='ps -eo pid,ppid,rss,vsize,pcpu,cmd --sort=vsize'
alias od='objdump -Sld'
alias p4b='bash ~/bin/p4bak.sh'
alias p4d='p4 diff ...'
alias p='ping google.com'
alias pst='pstree -G'
alias rba='rpmbuild -ba'
alias rbb='rpmbuild -bb'
alias saar='sudo apt-get autoremove'
#alias sai='sudo apt-get install'
#alias sar='sudo apt-get remove --purge'
alias saud='sudo apt-get dist-upgrade -y'
alias saug='sudo apt-get upgrade'
alias sau='sudo apt-get update'
alias scp='scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias sda='sudo depmod -a'
alias sdc='sudo dmesg -c'
alias sdn='sudo dmesg -n8'
alias sd='sudo dhclient'
alias sei='sudo ethtool -i'
alias sek='sudo ethtool -k'
alias seK='sudo ethtool -K'
alias se='sudo ethtool'
alias si='sudo ifconfig'
alias SI='sudo init 0'
alias skd='sudo killall dhclient'
alias sk='sudo killall -9'
alias smi='sudo make install'
alias spand='/google/data/rw/projects/spanner/links/span.daily'
alias spz='sudo pain -Z'
#alias ssh='ssh -y -Y -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias ss='sudo setpci -s'
alias s='sudo'
alias svd='sudo killall vpnc'
alias sv='sudo killall vpnc; sudo vpnc'
#alias syi='sudo yum install -y'
#alias syr='sudo yum remove'
alias sys='sudo yum search'
alias sy='sync';
#alias syu='sudo yum update'
alias ta='tmux attach'
alias tbzh='tar --exclude=*.o --exclude=*.ko --exclude=*.cmd --exclude=*.unsigned --exclude=*.sig --exclude=*.digest --exclude=cscope.* --exclude=tags --exclude=vmlinux --exclude=.tmp_vmlinu* -jcvfh'
alias tbz='tar --exclude=*.o --exclude=*.ko --exclude=*.cmd --exclude=*.unsigned --exclude=*.sig --exclude=*.digest --exclude=cscope.* --exclude=tags --exclude=vmlinux --exclude=.tmp_vmlinu* -jcvf'
alias tf='tree -A'
alias tm='tmux'
alias t='tree -Ad'
alias tz='tar --exclude=*.o --exclude=*.ko --exclude=*.cmd --exclude=*.unsigned --exclude=*.sig --exclude=*.digest --exclude=cscope.* --exclude=tags --exclude=vmlinux --exclude=.tmp_vmlinu* -zcvf'
alias ua='uname -a'
alias vef='sudo vim /etc/fstab'
alias vg="echo sudo vim /boot/grub/grub.conf && sudo vim /boot/grub/grub.conf"
alias vh="echo sudo vim /etc/hosts && sudo vim /etc/hosts"
alias vi=vim
alias vlm='sudo tail -f /var/log/messages'
alias vn='vncserver -geometry 1900x1000'
alias xr='xrandr --output DP-2 --right-of DP-1'
alias xv='xvncviewer -noraiseonbeep'
alias yw='yum whatprovides'
alias zi='zenity --info'

#Tintri
alias hbd='hg bookmark -d'
alias hd='hg vd'
alias hdc='hg diff -g -c .'
alias hgcl='hg clone'
alias hgb='hg bookmarks'
alias hgca='hg commit --amend'
alias hgg='hg log -G -b .'
#alias hgd='hg diff -g -p -I "listfile:$HOME/hgdiffinc.txt"'
alias hgh='hg histedit'
alias hghc='hg histedit --continue'
alias hgi='hg in -b .'
alias hgk='hg backup'
alias hgo='hg out -n -r .'
alias HGP='hg purge --all'
alias HGR='hg revert --all'
alias hgs='hg status'
alias hgv='hg backup && hg review'
alias ltx='ls -lrt ../../distro_bld/local_rpms/RPMS/x86_64/txos*'
alias nvm='ssh -y -Y nsujir-vm'
alias nws='ssh -y -Y nsujir-ws'
alias pxe='ssh -y -Y pxesrv1'
alias tvm='ssh -y -Y root@test-vm205'
alias uvm='ssh -y -Y nsujir-ubuntu14'

#alias rsv='rsync -av --exclude="*.swp" $HOME/nithins-configs nsujir-ws:'
alias upgl='cd; /auto/e2e/bin/UpgradeTools.py install --rpmpath `readlink latest` '
alias upglu='cd; /auto/e2e/bin/UpgradeTools.py upgrade --rpmpath `readlink latest` '
alias vd='P4DIFF=vimdiff g4 diff'

